var n1=6;
var n2=7;
console.log(n1<n2);
console.log(n1<=n2);
console.log(n1>n2);
console.log(n1>=n2);
console.log(n1==n2);
console.log(n1!=n2);
console.log(2==2);
console.log(2==`2`);
console.log(3!=2);
console.log('hello'!='Hello');
console.log(2===2);
console.log(2===`2`);
console.log(2!=='2');
console.log(2!==2);